language: java

services:
- docker

jdk:
- openjdk11

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::6}

before_script:
  - export REPO=$DOCKER_USERNAME/gemeente-nlakbonline
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $COMMIT ; fi`
  - docker build -f ./Dockerfile-assemble -t $REPO:$TAG .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $REPO:$TAG

script: true

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/