gemeente:
  oauth2:
    client:
      clientId: first-app
      clientSecret: '12345'
      accessTokenUri: http://gemeente-auth/oauth/token
      userAuthorizationUri: http://gemeente-auth/oauth/authorize
      authenticationScheme: header
      clientAuthenticationScheme: header
    resource:
      userInfoUri: http://gemeente-auth/user/me

server:
  port: 8081

logging:
  level:
    org:
      apache:
        http: DEBUG