gemeente:
  oauth2:
    client:
      clientId: first-app
      clientSecret: '12345'
      accessTokenUri: http://gemeente-auth/oauth/token
      userAuthorizationUri: http://gemeente-auth/oauth/authorize
      authenticationScheme: header
      clientAuthenticationScheme: header
    resource:
      userInfoUri: http://gemeente-auth/user/me

datasource:
  akb:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:mysql://db/gemeente-akb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'gemeente-akb'
    password: 'gemeente-akb'
    hikari:
      idle-timeout: 10000

content:
  resources:
    directory: /home/jelle/Environment/
  pages:
    pages[0]:
      id: welcome
      title: Welkom
      footer: '&copy; Ichthus 2018'
      introduction: AKB 2019 is weer begonnen! U doet toch ook mee?!
      content: De actie kerkbalans (AKB) is de jaarlijks actie van de PKN. Ook als wijkgemeente Ichthus doen we hieraan mee en hiermee worden grotendeels de jaarlijkse begroting bekostigd.
    pages[1]:
      id: give
      title: Kerkbalans 2019
      footer: '&copy; Ichthus 2018'
      introduction: Bedankt dat u overweegt ook dit jaar de wijkgemeente Ichthus te ondersteunen!
      content: Hieronder kunt u aangeven welk bedrag u wilt toezeggen. Het bedrag is het totale bedrage. Als u maandelijks wilt betalen, kies dan de maanden waarin u wilt betalen. Het bedrag wordt dan evenredig verdeeld.
    pages[2]:
      id: default
      title: Default
      footer: '&copy; Ichthus 2018'

server:
  port: 8081

logging:
  level:
    org:
      apache:
        http: DEBUG