gemeente:
  oauth2:
    client:
      clientId: first-app
      clientSecret: '12345'
      accessTokenUri: http://gemeente-auth/oauth/token
      userAuthorizationUri: http://gemeente-auth/oauth/authorize
      authenticationScheme: header
      clientAuthenticationScheme: header
    resource:
      userInfoUri: http://gemeente-auth/user/me

account:
  service:
    uri: http://gemeente-auth/user/account

datasource:
  akb:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:mysql://db/gemeente-akb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'gemeente-akb'
    password: 'gemeente-akb'
    hikari:
      idle-timeout: 10000

content:
  resources:
    directory: /home/jelle/Environment/
  automatic-payment-information:
    creditorName: 'TestCreditor at Amsterdam'
    creditorId: NL1234567890
    dayOfMonth: 25
    mandateReferencePrefix: 'RET'
    mandateReferencePostfix: 20187654
  manual-payment-information:
    creditorName: 'TestCreditor at Amsterdam'
    bankAccountNumber: 'NL12 ABNA 0123 4567 89'
  pages:
    pages[0]:
      id: welcome
      title: Welkom
      footer: '&copy; Ichthus 2018'
      introduction: AKB 2019 is weer begonnen! U doet toch ook mee?!
      content: De actie kerkbalans (AKB) is de jaarlijkse actie van de PKN. Ook als wijkgemeente Ichthus doen we hieraan mee en hiermee worden grotendeels de jaarlijkse begroting bekostigd.
    pages[1]:
      id: give
      title: Kerkbalans 2019
      footer: '&copy; Ichthus 2018'
      introduction: Bedankt dat u overweegt ook dit jaar de wijkgemeente Ichthus te ondersteunen!
      content: Geef hieronder het totale bedrag aan dat u toezegt. Kruis de maand(en) aan waarin u wilt betalen. Als u meer maanden aankruist wordt het bedrag evenredig verdeeld.
    pages[2]:
      id: give-bank-transfer
      title: Kerkbalans 2019
      footer: '&copy; Ichthus 2018'
      introduction: U wilt betalen per bankopdracht
      content: Controleer hieronder uw bijdrage.
    pages[3]:
      id: give-bank-automatic
      title: Kerkbalans 2019
      footer: '&copy; Ichthus 2018'
      introduction: U wilt betalen per automatische incasso
      content: Controleer hieronder uw bijdrage.
    pages[4]:
      id: default
      title: Default
      footer: '&copy; Ichthus 2018'

server:
  port: 8081

logging:
  level:
    org:
      apache:
        http: DEBUG