gemeente:
  oauth2:
    client:
      clientId: first-app
      clientSecret: '12345'
      accessTokenUri: http://gemeente-auth/oauth/token
      userAuthorizationUri: http://gemeente-auth/oauth/authorize
      authenticationScheme: header
      clientAuthenticationScheme: header
    resource:
      userInfoUri: http://gemeente-auth/user/me

datasource:
  akb:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:mysql://db/gemeente-akb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'gemeente-akb'
    password: 'gemeente-akb'
    hikari:
      idle-timeout: 10000

server:
  port: 8081

logging:
  level:
    org:
      apache:
        http: DEBUG